import type { CertificationContent } from "./types";

export const cka: CertificationContent = {
  slug: "cka",
  name: "Certified Kubernetes Administrator",
  shortName: "CKA",
  description:
    "The CKA program provides assurance that CKAs have the skills, knowledge, and competency to perform the responsibilities of Kubernetes administrators. Focus on cluster architecture, workloads, services, networking, storage, and troubleshooting.",
  icon: "⚙️",
  color: "#326CE5",
  difficulty: "intermediate",
  estimatedHours: 40,
  order: 2,
  exam: { questions: 15, minutes: 30, passPercent: 66 },
  modules: [
    {
      slug: "cluster-architecture",
      name: "Cluster Architecture, Installation & Configuration",
      description: "Setting up and configuring Kubernetes clusters (25% of exam)",
      xp: 300,
      lessons: [
        { type: "reading", slug: "rbac-authorization", title: "RBAC Authorization", duration: 20, xp: 60 },
        { type: "reading", slug: "kubeadm-cluster-setup", title: "Cluster Setup with kubeadm", duration: 20, xp: 60 },
        {
          type: "quiz",
          slug: "cluster-architecture-quiz",
          title: "Cluster Architecture Quiz",
          duration: 10,
          xp: 75,
          intro: "Test your knowledge of RBAC and cluster installation.",
          questions: [
            {
              question: "Which object grants the permissions of a Role to a user or ServiceAccount?",
              type: "multiple_choice",
              options: ["RoleBinding", "ClusterRole", "ServiceAccount", "NetworkPolicy"],
              answer: "RoleBinding",
              explanation: "A RoleBinding attaches a Role (or ClusterRole) to subjects within one namespace.",
            },
            {
              question: "A Role can grant access to resources in every namespace of the cluster.",
              type: "true_false",
              options: ["True", "False"],
              answer: "False",
              explanation: "Roles are namespaced. Use a ClusterRole with a ClusterRoleBinding for cluster-wide access.",
            },
            {
              question: "Which command initialises a new control plane node with kubeadm?",
              type: "multiple_choice",
              options: ["kubeadm init", "kubeadm join", "kubeadm start", "kubectl init"],
              answer: "kubeadm init",
              explanation: "kubeadm init bootstraps the control plane. Worker nodes are added with kubeadm join.",
            },
            {
              question: "Which of these are valid RBAC verbs? (Select all that apply)",
              type: "multi_select",
              options: ["get", "list", "watch", "execute"],
              answer: ["get", "list", "watch"],
              explanation: "Kubernetes RBAC verbs include get, list, watch, create, update, patch and delete. 'execute' isn't one of them.",
            },
            {
              question: "How do you check whether a ServiceAccount 'ci' in namespace 'dev' may create Pods?",
              type: "multiple_choice",
              options: [
                "kubectl auth can-i create pods --as=system:serviceaccount:dev:ci -n dev",
                "kubectl get rolebindings --user=ci",
                "kubectl describe sa ci --permissions",
                "kubeadm check permissions ci",
              ],
              answer: "kubectl auth can-i create pods --as=system:serviceaccount:dev:ci -n dev",
              explanation: "kubectl auth can-i with --as impersonates a subject and asks the API server whether the action is allowed.",
            },
          ],
        },
        {
          type: "lab",
          slug: "rbac-lab",
          title: "Lab: RBAC for a Deployment Bot",
          duration: 20,
          xp: 120,
          intro: "Give a CI ServiceAccount exactly the permissions it needs.",
          timeLimit: 25,
          hints: [
            "kubectl create serviceaccount deployer -n dev",
            "kubectl create role pod-manager --verb=get,list,create,delete --resource=pods -n dev",
            "kubectl create rolebinding deployer-binding --role=pod-manager --serviceaccount=dev:deployer -n dev",
            "kubectl auth can-i delete pods --as=system:serviceaccount:dev:deployer -n dev",
          ],
          initialState: [{ kind: "Namespace", name: "dev" }],
          checks: [
            { type: "exists", description: "ServiceAccount deployer exists in dev", kind: "ServiceAccount", name: "deployer", namespace: "dev" },
            { type: "exists", description: "Role pod-manager allows get/list/create/delete on pods", kind: "Role", name: "pod-manager", namespace: "dev", match: { verbs: ["get", "list", "create", "delete"], resources: ["pods"] } },
            { type: "exists", description: "RoleBinding deployer-binding binds pod-manager to deployer", kind: "RoleBinding", name: "deployer-binding", namespace: "dev", match: { role: "pod-manager", subjects: ["ServiceAccount:dev:deployer"] } },
            { type: "command", description: "Verified access with kubectl auth can-i", pattern: "auth\\s+can-i" },
          ],
        },
      ],
    },
    {
      slug: "workloads-scheduling",
      name: "Workloads & Scheduling",
      description: "Managing pods, deployments, and scheduling (15% of exam)",
      xp: 250,
      lessons: [
        { type: "reading", slug: "deployments-rollouts", title: "Deployments and Rolling Updates", duration: 15, xp: 50 },
        { type: "reading", slug: "scheduling-and-maintenance", title: "Scheduling and Node Maintenance", duration: 20, xp: 60 },
        {
          type: "quiz",
          slug: "workloads-quiz",
          title: "Workloads & Scheduling Quiz",
          duration: 10,
          xp: 75,
          intro: "Test your knowledge of rollouts, taints and node maintenance.",
          questions: [
            {
              question: "Which command reverts a Deployment to its previous revision?",
              type: "multiple_choice",
              options: ["kubectl rollout undo deployment/web", "kubectl rollback deployment/web", "kubectl revert deployment/web", "kubectl set image --previous"],
              answer: "kubectl rollout undo deployment/web",
              explanation: "kubectl rollout undo returns to the previous revision, or to a specific one with --to-revision.",
            },
            {
              question: "Which taint effect also evicts Pods that are already running on the node?",
              type: "multiple_choice",
              options: ["NoSchedule", "PreferNoSchedule", "NoExecute", "NoEvict"],
              answer: "NoExecute",
              explanation: "NoExecute blocks new Pods and evicts running Pods that don't tolerate the taint.",
            },
            {
              question: "kubectl drain automatically marks the node unschedulable.",
              type: "true_false",
              options: ["True", "False"],
              answer: "True",
              explanation: "drain cordons the node first, then evicts its Pods. You must uncordon it afterwards.",
            },
            {
              question: "Why does kubectl drain fail without --ignore-daemonsets on most nodes?",
              type: "multiple_choice",
              options: [
                "DaemonSet Pods would be recreated on the same node immediately",
                "DaemonSets can't be deleted",
                "The node is still Ready",
                "The scheduler is paused",
              ],
              answer: "DaemonSet Pods would be recreated on the same node immediately",
              explanation: "The DaemonSet controller ignores cordons and puts its Pods back, so drain asks you to explicitly ignore them.",
            },
            {
              question: "Which settings control a rolling update's pace? (Select all that apply)",
              type: "multi_select",
              options: ["maxSurge", "maxUnavailable", "replicas", "revisionHistoryLimit"],
              answer: ["maxSurge", "maxUnavailable"],
              explanation: "maxSurge limits extra Pods above the desired count, and maxUnavailable limits how many can be down during the update.",
            },
          ],
        },
        {
          type: "lab",
          slug: "rolling-update-lab",
          title: "Lab: Rolling Update and Rollback",
          duration: 20,
          xp: 120,
          intro: "Update a Deployment, scale it and roll back a bad release.",
          timeLimit: 25,
          hints: [
            "kubectl set image deployment/api nginx=nginx:1.26",
            "kubectl rollout status deployment/api and kubectl rollout history deployment/api",
            "kubectl scale deployment api --replicas=5",
            "kubectl rollout undo deployment/api",
          ],
          initialState: [
            { kind: "Deployment", name: "api", namespace: "default", image: "nginx:1.25", replicas: 3, revisions: ["nginx:1.25"], labels: { app: "api" } },
          ],
          checks: [
            { type: "command", description: "Updated the image with kubectl set image", pattern: "set\\s+image\\s+(deployment|deploy)[\\s/]+api\\b.*nginx:1\\.26" },
            { type: "command", description: "Rolled back with kubectl rollout undo", pattern: "rollout\\s+undo" },
            { type: "exists", description: "api runs nginx:1.25 with 5 replicas", kind: "Deployment", name: "api", namespace: "default", match: { image: "nginx:1.25", replicas: 5 } },
          ],
        },
        {
          type: "lab",
          slug: "node-maintenance-lab",
          title: "Lab: Node Maintenance and Taints",
          duration: 25,
          xp: 150,
          intro: "Drain a node for maintenance and dedicate another to GPU workloads.",
          timeLimit: 30,
          hints: [
            "kubectl drain worker-1 --ignore-daemonsets",
            "kubectl get pods -o wide",
            "kubectl uncordon worker-1",
            "kubectl label node worker-2 accelerator=nvidia",
            "kubectl taint nodes worker-2 gpu=true:NoSchedule",
          ],
          initialState: [
            { kind: "Deployment", name: "shop", namespace: "default", image: "nginx:1.27", replicas: 4, revisions: ["nginx:1.27"], labels: { app: "shop" } },
          ],
          checks: [
            { type: "command", description: "Drained worker-1", pattern: "drain\\s+worker-1\\b.*--ignore-daemonsets" },
            { type: "exists", description: "worker-1 is schedulable again", kind: "Node", name: "worker-1", match: { schedulable: true } },
            { type: "exists", description: "worker-2 is labelled and tainted for GPUs", kind: "Node", name: "worker-2", match: { labels: { accelerator: "nvidia" }, taints: ["gpu=true:NoSchedule"] } },
            { type: "pods", description: "4 shop Pods run, none on worker-2", namespace: "default", selector: { app: "shop" }, running: 4, notOnNode: "worker-2" },
          ],
        },
      ],
    },
    {
      slug: "services-networking",
      name: "Services & Networking",
      description: "Service types, endpoints, DNS and kube-proxy (20% of exam)",
      xp: 250,
      lessons: [
        { type: "reading", slug: "services-and-networking", title: "Services and Cluster Networking", duration: 20, xp: 60 },
        {
          type: "quiz",
          slug: "networking-quiz",
          title: "Services & Networking Quiz",
          duration: 10,
          xp: 75,
          intro: "Test your understanding of Services and cluster networking.",
          questions: [
            {
              question: "What is the default NodePort range?",
              type: "multiple_choice",
              options: ["30000-32767", "1-1024", "8000-9000", "20000-25000"],
              answer: "30000-32767",
              explanation: "NodePorts are allocated from 30000-32767 unless the API server's --service-node-port-range is changed.",
            },
            {
              question: "What is the fully qualified DNS name of Service 'api' in namespace 'shop'?",
              type: "multiple_choice",
              options: ["api.shop.svc.cluster.local", "shop.api.cluster.local", "api.svc.shop.local", "api.cluster.shop"],
              answer: "api.shop.svc.cluster.local",
              explanation: "Service DNS names follow <service>.<namespace>.svc.cluster.local.",
            },
            {
              question: "A Service shows no endpoints. What are the most likely causes? (Select all that apply)",
              type: "multi_select",
              options: [
                "The selector doesn't match any Pod labels",
                "The matching Pods aren't ready",
                "The Service type is ClusterIP",
                "The namespace has too many Services",
              ],
              answer: ["The selector doesn't match any Pod labels", "The matching Pods aren't ready"],
              explanation: "Endpoints only include ready Pods whose labels match the selector. The Service type doesn't affect endpoints.",
            },
            {
              question: "Which component programs iptables or IPVS rules for Services on each node?",
              type: "multiple_choice",
              options: ["kube-proxy", "kubelet", "CoreDNS", "kube-controller-manager"],
              answer: "kube-proxy",
              explanation: "kube-proxy watches Services and EndpointSlices and programs the node's forwarding rules.",
            },
            {
              question: "A LoadBalancer Service also gets a ClusterIP and a NodePort.",
              type: "true_false",
              options: ["True", "False"],
              answer: "True",
              explanation: "LoadBalancer builds on NodePort, which builds on ClusterIP. The cloud load balancer forwards to the node ports.",
            },
          ],
        },
        {
          type: "lab",
          slug: "expose-service-lab",
          title: "Lab: Expose a Service with NodePort",
          duration: 15,
          xp: 100,
          intro: "Expose an application outside the cluster.",
          timeLimit: 20,
          hints: [
            "kubectl expose deployment frontend --type=NodePort --name=frontend-svc --port=80 --target-port=8080 -n web",
            "kubectl scale deployment frontend --replicas=3 -n web",
            "kubectl describe svc frontend-svc -n web",
          ],
          initialState: [
            { kind: "Namespace", name: "web" },
            { kind: "Deployment", name: "frontend", namespace: "web", image: "nginx:1.27", replicas: 2, revisions: ["nginx:1.27"], labels: { app: "frontend" } },
          ],
          checks: [
            { type: "exists", description: "frontend-svc is a NodePort on port 80 to 8080", kind: "Service", name: "frontend-svc", namespace: "web", match: { type: "NodePort", port: 80, targetPort: 8080, selector: { app: "frontend" } } },
            { type: "exists", description: "frontend runs 3 replicas", kind: "Deployment", name: "frontend", namespace: "web", match: { replicas: 3 } },
          ],
        },
      ],
    },
  ],
};
