import type { CertificationContent } from "./types";

export const ckad: CertificationContent = {
  slug: "ckad",
  name: "Certified Kubernetes Application Developer",
  shortName: "CKAD",
  description:
    "The CKAD exam certifies that candidates can design, build, configure, and expose cloud native applications for Kubernetes. Focus on application design, deployment, observability, and services.",
  icon: "🚀",
  color: "#8B5CF6",
  difficulty: "intermediate",
  estimatedHours: 35,
  order: 3,
  exam: { questions: 15, minutes: 30, passPercent: 66 },
  modules: [
    {
      slug: "app-design-build",
      name: "Application Design and Build",
      description: "Designing and building containerized applications (20% of exam)",
      xp: 250,
      lessons: [
        { type: "reading", slug: "multi-container-pods", title: "Multi-Container Pod Patterns", duration: 15, xp: 50 },
        { type: "reading", slug: "labels-and-selectors", title: "Labels, Selectors and Annotations", duration: 12, xp: 50 },
        {
          type: "quiz",
          slug: "app-design-quiz",
          title: "Application Design Quiz",
          duration: 10,
          xp: 75,
          intro: "Test your knowledge of Pod design and labels.",
          questions: [
            {
              question: "Which multi-container pattern runs a helper container that extends the main container, such as a log shipper?",
              type: "multiple_choice",
              options: ["Sidecar", "Init container", "DaemonSet", "Operator"],
              answer: "Sidecar",
              explanation: "A sidecar runs alongside the main container for the Pod's lifetime and adds functionality such as log shipping or proxying.",
            },
            {
              question: "Init containers run to completion before the app containers start.",
              type: "true_false",
              options: ["True", "False"],
              answer: "True",
              explanation: "Init containers run sequentially, and each must succeed before the next one, and finally the app containers, start.",
            },
            {
              question: "Which can be used in a label selector? (Select all that apply)",
              type: "multi_select",
              options: ["Labels", "Annotations", "Pod names", "Container images"],
              answer: ["Labels"],
              explanation: "Only labels can be selected on. Annotations hold non-identifying metadata.",
            },
            {
              question: "How do you change an existing label value on a Pod?",
              type: "multiple_choice",
              options: [
                "kubectl label pod api env=prod --overwrite",
                "kubectl annotate pod api env=prod",
                "kubectl set label pod api env=prod",
                "kubectl edit label api env=prod",
              ],
              answer: "kubectl label pod api env=prod --overwrite",
              explanation: "kubectl label refuses to change an existing value unless you pass --overwrite.",
            },
            {
              question: "Containers in the same Pod can reach each other on localhost.",
              type: "true_false",
              options: ["True", "False"],
              answer: "True",
              explanation: "All containers in a Pod share one network namespace, so they share an IP and can use localhost.",
            },
          ],
        },
        {
          type: "lab",
          slug: "labels-lab",
          title: "Lab: Organise Pods with Labels",
          duration: 15,
          xp: 100,
          intro: "Use labels to organise and query Pods.",
          timeLimit: 20,
          hints: [
            "kubectl label pods api-1 api-2 env=prod",
            "kubectl label pod cache env=staging",
            "kubectl run debug --image=busybox:1.36 --labels=app=debug,env=dev",
            "kubectl get pods -l env=prod",
          ],
          initialState: [
            { kind: "Pod", name: "api-1", namespace: "default", image: "node:22-alpine", node: "worker-1", owner: null, labels: { app: "api" } },
            { kind: "Pod", name: "api-2", namespace: "default", image: "node:22-alpine", node: "worker-2", owner: null, labels: { app: "api" } },
            { kind: "Pod", name: "cache", namespace: "default", image: "redis:7.4", node: "worker-1", owner: null, labels: { app: "redis" } },
          ],
          checks: [
            { type: "exists", description: "api-1 is labelled env=prod", kind: "Pod", name: "api-1", match: { labels: { env: "prod" } } },
            { type: "exists", description: "api-2 is labelled env=prod", kind: "Pod", name: "api-2", match: { labels: { env: "prod" } } },
            { type: "exists", description: "cache is labelled env=staging", kind: "Pod", name: "cache", match: { labels: { env: "staging" } } },
            { type: "exists", description: "debug runs busybox:1.36 with app=debug,env=dev", kind: "Pod", name: "debug", match: { image: "busybox:1.36", labels: { app: "debug", env: "dev" } } },
            { type: "command", description: "Queried Pods with a label selector", pattern: "get\\s+(pods|pod|po)\\b.*(-l|--selector)[\\s=]+['\"]?env=prod" },
          ],
        },
      ],
    },
    {
      slug: "app-configuration",
      name: "Application Environment & Configuration",
      description: "ConfigMaps, Secrets and configuration best practices (25% of exam)",
      xp: 250,
      lessons: [
        { type: "reading", slug: "configmaps-and-secrets", title: "ConfigMaps and Secrets", duration: 15, xp: 50 },
        {
          type: "quiz",
          slug: "configuration-quiz",
          title: "Configuration Quiz",
          duration: 10,
          xp: 75,
          intro: "Test your knowledge of ConfigMaps and Secrets.",
          questions: [
            {
              question: "By default, how are Secret values stored in etcd?",
              type: "multiple_choice",
              options: ["Base64-encoded, not encrypted", "AES-256 encrypted", "Hashed with bcrypt", "Stored only in memory"],
              answer: "Base64-encoded, not encrypted",
              explanation: "Without an EncryptionConfiguration, Secrets are only base64-encoded in etcd. Enable encryption at rest to protect them.",
            },
            {
              question: "Environment variables injected from a ConfigMap update automatically in a running Pod when the ConfigMap changes.",
              type: "true_false",
              options: ["True", "False"],
              answer: "False",
              explanation: "Environment variables are read at container start. Mounted ConfigMap volumes update, env vars need a restart.",
            },
            {
              question: "Which field injects every key of a ConfigMap as environment variables?",
              type: "multiple_choice",
              options: ["envFrom.configMapRef", "env.valueFrom.configMapKeyRef", "volumes.configMap", "spec.configMap"],
              answer: "envFrom.configMapRef",
              explanation: "envFrom with configMapRef imports all keys. valueFrom.configMapKeyRef imports a single key.",
            },
            {
              question: "Which are good ways to protect Secrets? (Select all that apply)",
              type: "multi_select",
              options: [
                "Restrict get/list on secrets with RBAC",
                "Enable encryption at rest",
                "Commit them to Git as base64",
                "Store them in a ConfigMap instead",
              ],
              answer: ["Restrict get/list on secrets with RBAC", "Enable encryption at rest"],
              explanation: "Limit who can read Secrets and encrypt them in etcd. Base64 is an encoding, not protection.",
            },
            {
              question: "A Pod can reference a ConfigMap from a different namespace.",
              type: "true_false",
              options: ["True", "False"],
              answer: "False",
              explanation: "ConfigMaps and Secrets are namespaced, and Pods can only use ones in their own namespace.",
            },
          ],
        },
        {
          type: "lab",
          slug: "config-lab",
          title: "Lab: Configure an App",
          duration: 15,
          xp: 100,
          intro: "Create configuration and credentials for a new service.",
          timeLimit: 20,
          hints: [
            "kubectl create configmap app-config --from-literal=APP_MODE=production --from-literal=LOG_LEVEL=info -n shop",
            "kubectl create secret generic db-creds --from-literal=username=shop --from-literal=password=s3cure-pass -n shop",
            "kubectl describe secret db-creds -n shop",
          ],
          initialState: [{ kind: "Namespace", name: "shop" }],
          checks: [
            { type: "exists", description: "ConfigMap app-config has APP_MODE and LOG_LEVEL", kind: "ConfigMap", name: "app-config", namespace: "shop", match: { data: { APP_MODE: "production", LOG_LEVEL: "info" } } },
            { type: "exists", description: "Secret db-creds has username and password", kind: "Secret", name: "db-creds", namespace: "shop", match: { data: { username: "shop", password: "s3cure-pass" } } },
          ],
        },
      ],
    },
    {
      slug: "app-deployment",
      name: "Application Deployment",
      description: "Rollouts, blue/green and canary releases (20% of exam)",
      xp: 250,
      lessons: [
        { type: "reading", slug: "deployment-strategies", title: "Deployment Strategies", duration: 15, xp: 50 },
        {
          type: "quiz",
          slug: "deployment-quiz",
          title: "Deployment Strategies Quiz",
          duration: 10,
          xp: 75,
          intro: "Test your knowledge of release strategies.",
          questions: [
            {
              question: "Which strategy stops all old Pods before starting new ones?",
              type: "multiple_choice",
              options: ["Recreate", "RollingUpdate", "Canary", "Blue/green"],
              answer: "Recreate",
              explanation: "Recreate terminates every old Pod first, which causes downtime but guarantees two versions never run together.",
            },
            {
              question: "In a blue/green release, how is traffic usually switched to the new version?",
              type: "multiple_choice",
              options: [
                "Change the Service selector to the new version's labels",
                "Delete the old Pods one by one",
                "Restart the kubelet",
                "Scale the Service to zero",
              ],
              answer: "Change the Service selector to the new version's labels",
              explanation: "Both versions run in parallel, and updating the Service selector moves all traffic at once, which also makes rollback instant.",
            },
            {
              question: "With 3 stable replicas and 1 canary replica behind one Service, roughly what share of requests reach the canary?",
              type: "multiple_choice",
              options: ["25%", "50%", "10%", "75%"],
              answer: "25%",
              explanation: "The Service balances across all 4 matching Pods, so about 1 in 4 requests hits the canary.",
            },
            {
              question: "Which commands help during a problematic rollout? (Select all that apply)",
              type: "multi_select",
              options: ["kubectl rollout status", "kubectl rollout undo", "kubectl rollout history", "kubectl rollout delete"],
              answer: ["kubectl rollout status", "kubectl rollout undo", "kubectl rollout history"],
              explanation: "status watches progress, history lists revisions and undo rolls back. There is no 'rollout delete'.",
            },
            {
              question: "Changing only the replica count of a Deployment creates a new rollout revision.",
              type: "true_false",
              options: ["True", "False"],
              answer: "False",
              explanation: "Only changes to the Pod template (such as the image) create a new revision. Scaling does not.",
            },
          ],
        },
        {
          type: "lab",
          slug: "canary-lab",
          title: "Lab: Canary Release",
          duration: 20,
          xp: 120,
          intro: "Release a new version to a small share of Pods.",
          timeLimit: 25,
          hints: [
            "kubectl label deployment web-v1 track=stable",
            "kubectl create deployment web-v2 --image=nginx:1.27 --replicas=1",
            "kubectl label deployment web-v2 track=canary",
            "kubectl scale deployment web-v1 --replicas=3",
            "kubectl get pods -l track=canary",
          ],
          initialState: [
            { kind: "Deployment", name: "web-v1", namespace: "default", image: "nginx:1.26", replicas: 2, revisions: ["nginx:1.26"], labels: { app: "web-v1" } },
          ],
          checks: [
            { type: "exists", description: "web-v1 is labelled track=stable with 3 replicas", kind: "Deployment", name: "web-v1", match: { replicas: 3, labels: { track: "stable" } } },
            { type: "exists", description: "web-v2 runs nginx:1.27 with 1 replica, labelled track=canary", kind: "Deployment", name: "web-v2", match: { image: "nginx:1.27", replicas: 1, labels: { track: "canary" } } },
            { type: "pods", description: "Exactly one canary Pod is running", namespace: "default", selector: { track: "canary" }, running: 1 },
          ],
        },
      ],
    },
  ],
};
