import type { CertificationContent } from "./types";

export const cks: CertificationContent = {
  slug: "cks",
  name: "Certified Kubernetes Security Specialist",
  shortName: "CKS",
  description:
    "The CKS program provides assurance that a CKS has the skills, knowledge, and competency to secure container-based applications and Kubernetes platforms. Covers cluster setup, system hardening, supply chain security, and runtime security.",
  icon: "🛡️",
  color: "#EF4444",
  difficulty: "advanced",
  estimatedHours: 50,
  order: 4,
  exam: { questions: 15, minutes: 30, passPercent: 67 },
  modules: [
    {
      slug: "cluster-hardening",
      name: "Cluster Hardening",
      description: "Securing the Kubernetes cluster (15% of exam)",
      xp: 350,
      lessons: [
        { type: "reading", slug: "network-policies", title: "Network Policies", duration: 20, xp: 60 },
        { type: "reading", slug: "least-privilege-rbac", title: "Least-Privilege RBAC", duration: 15, xp: 60 },
        {
          type: "quiz",
          slug: "hardening-quiz",
          title: "Cluster Hardening Quiz",
          duration: 10,
          xp: 75,
          intro: "Test your knowledge of NetworkPolicies and RBAC hardening.",
          questions: [
            {
              question: "What happens to traffic in a namespace with no NetworkPolicies?",
              type: "multiple_choice",
              options: ["All traffic is allowed", "All traffic is denied", "Only DNS is allowed", "Only same-namespace traffic is allowed"],
              answer: "All traffic is allowed",
              explanation: "Pods are non-isolated by default. Once a policy selects a Pod, only the traffic that policy allows gets through.",
            },
            {
              question: "A NetworkPolicy with podSelector: {} and policyTypes: [Ingress] but no ingress rules does what?",
              type: "multiple_choice",
              options: [
                "Denies all ingress to every Pod in the namespace",
                "Allows all ingress",
                "Denies all egress",
                "Has no effect",
              ],
              answer: "Denies all ingress to every Pod in the namespace",
              explanation: "The empty selector selects all Pods, and with no ingress rules nothing is allowed in. It's the classic default-deny policy.",
            },
            {
              question: "NetworkPolicies work on any cluster, whatever CNI plugin is installed.",
              type: "true_false",
              options: ["True", "False"],
              answer: "False",
              explanation: "The CNI plugin must implement NetworkPolicy (Calico and Cilium do, basic Flannel doesn't). Otherwise policies are silently ignored.",
            },
            {
              question: "Which RBAC grants are red flags for a workload ServiceAccount? (Select all that apply)",
              type: "multi_select",
              options: [
                "verbs: [\"*\"] on resources: [\"*\"]",
                "A binding to cluster-admin",
                "get and list on secrets across the namespace",
                "get on its own ConfigMap",
              ],
              answer: ["verbs: [\"*\"] on resources: [\"*\"]", "A binding to cluster-admin", "get and list on secrets across the namespace"],
              explanation: "Wildcards, cluster-admin and broad Secret access all give far more than a workload usually needs.",
            },
            {
              question: "Which Pod setting prevents the ServiceAccount token from being mounted?",
              type: "multiple_choice",
              options: [
                "automountServiceAccountToken: false",
                "serviceAccountName: none",
                "readOnlyRootFilesystem: true",
                "hostNetwork: false",
              ],
              answer: "automountServiceAccountToken: false",
              explanation: "Setting automountServiceAccountToken to false on the Pod or ServiceAccount stops the API token from being mounted.",
            },
          ],
        },
        {
          type: "lab",
          slug: "least-privilege-lab",
          title: "Lab: Remove Excessive Permissions",
          duration: 20,
          xp: 150,
          intro: "Replace a wildcard Role with least-privilege access.",
          timeLimit: 25,
          hints: [
            "kubectl auth can-i delete secrets --as=system:serviceaccount:payments:reporter -n payments",
            "kubectl delete rolebinding reporter-binding -n payments && kubectl delete role too-broad -n payments",
            "kubectl create role pod-reader --verb=get,list,watch --resource=pods -n payments",
            "kubectl create rolebinding reporter-read --role=pod-reader --serviceaccount=payments:reporter -n payments",
          ],
          initialState: [
            { kind: "Namespace", name: "payments" },
            { kind: "ServiceAccount", name: "reporter", namespace: "payments" },
            { kind: "Role", name: "too-broad", namespace: "payments", verbs: ["*"], resources: ["*"] },
            { kind: "RoleBinding", name: "reporter-binding", namespace: "payments", role: "too-broad", subjects: ["ServiceAccount:payments:reporter"] },
          ],
          checks: [
            { type: "absent", description: "RoleBinding reporter-binding is removed", kind: "RoleBinding", name: "reporter-binding", namespace: "payments" },
            { type: "absent", description: "Role too-broad is removed", kind: "Role", name: "too-broad", namespace: "payments" },
            { type: "exists", description: "Role pod-reader allows get/list/watch on pods", kind: "Role", name: "pod-reader", namespace: "payments", match: { verbs: ["get", "list", "watch"], resources: ["pods"] } },
            { type: "exists", description: "reporter-read binds pod-reader to reporter", kind: "RoleBinding", name: "reporter-read", namespace: "payments", match: { role: "pod-reader", subjects: ["ServiceAccount:payments:reporter"] } },
            { type: "command", description: "Audited access with kubectl auth can-i", pattern: "auth\\s+can-i" },
          ],
        },
      ],
    },
    {
      slug: "pod-security",
      name: "Minimize Microservice Vulnerabilities",
      description: "Pod Security Standards and security contexts (20% of exam)",
      xp: 300,
      lessons: [
        { type: "reading", slug: "pod-security-standards", title: "Pod Security Standards", duration: 15, xp: 60 },
        {
          type: "quiz",
          slug: "pod-security-quiz",
          title: "Pod Security Quiz",
          duration: 10,
          xp: 75,
          intro: "Test your knowledge of Pod Security Admission.",
          questions: [
            {
              question: "Which Pod Security Standard level requires containers to run as non-root and drop all capabilities?",
              type: "multiple_choice",
              options: ["restricted", "baseline", "privileged", "hardened"],
              answer: "restricted",
              explanation: "restricted is the hardened profile: non-root, no privilege escalation, drop ALL capabilities, seccomp RuntimeDefault.",
            },
            {
              question: "Which Pod Security Admission mode rejects violating Pods?",
              type: "multiple_choice",
              options: ["enforce", "audit", "warn", "deny"],
              answer: "enforce",
              explanation: "enforce rejects, audit records in the audit log and warn shows a warning to the user.",
            },
            {
              question: "Labelling a namespace with enforce=restricted immediately evicts running Pods that violate the policy.",
              type: "true_false",
              options: ["True", "False"],
              answer: "False",
              explanation: "Admission only checks Pods when they're created or updated. Existing Pods keep running.",
            },
            {
              question: "Which securityContext settings are required by the restricted level? (Select all that apply)",
              type: "multi_select",
              options: [
                "allowPrivilegeEscalation: false",
                "runAsNonRoot: true",
                "capabilities.drop: [\"ALL\"]",
                "privileged: true",
              ],
              answer: ["allowPrivilegeEscalation: false", "runAsNonRoot: true", "capabilities.drop: [\"ALL\"]"],
              explanation: "restricted forbids privileged containers and requires non-root, no privilege escalation and dropping all capabilities.",
            },
            {
              question: "What replaced PodSecurityPolicy, which was removed in Kubernetes 1.25?",
              type: "multiple_choice",
              options: ["Pod Security Admission", "NetworkPolicy", "OPA only", "SecurityContextConstraints"],
              answer: "Pod Security Admission",
              explanation: "The built-in Pod Security Admission controller replaced PodSecurityPolicy. Gatekeeper and Kyverno handle custom policies.",
            },
          ],
        },
        {
          type: "lab",
          slug: "pod-security-lab",
          title: "Lab: Enforce Pod Security Standards",
          duration: 15,
          xp: 120,
          intro: "Apply Pod Security Admission levels with namespace labels.",
          timeLimit: 20,
          hints: [
            "kubectl label namespace prod pod-security.kubernetes.io/enforce=restricted",
            "kubectl label namespace sandbox pod-security.kubernetes.io/enforce=baseline pod-security.kubernetes.io/warn=restricted",
            "kubectl get ns --show-labels",
          ],
          initialState: [
            { kind: "Namespace", name: "prod" },
            { kind: "Namespace", name: "sandbox" },
          ],
          checks: [
            { type: "exists", description: "prod enforces restricted", kind: "Namespace", name: "prod", match: { labels: { "pod-security.kubernetes.io/enforce": "restricted" } } },
            { type: "exists", description: "sandbox enforces baseline", kind: "Namespace", name: "sandbox", match: { labels: { "pod-security.kubernetes.io/enforce": "baseline" } } },
            { type: "exists", description: "sandbox warns on restricted", kind: "Namespace", name: "sandbox", match: { labels: { "pod-security.kubernetes.io/warn": "restricted" } } },
          ],
        },
      ],
    },
    {
      slug: "supply-chain-security",
      name: "Supply Chain Security",
      description: "Image hygiene, scanning and secrets management (20% of exam)",
      xp: 300,
      lessons: [
        { type: "reading", slug: "supply-chain-security", title: "Supply Chain and Secrets Security", duration: 15, xp: 60 },
        {
          type: "quiz",
          slug: "supply-chain-quiz",
          title: "Supply Chain Quiz",
          duration: 10,
          xp: 75,
          intro: "Test your knowledge of image and secrets hygiene.",
          questions: [
            {
              question: "Which image reference is guaranteed to be immutable?",
              type: "multiple_choice",
              options: ["nginx@sha256:<digest>", "nginx:latest", "nginx:1.27", "nginx:stable"],
              answer: "nginx@sha256:<digest>",
              explanation: "Tags can be moved to a different image. A digest identifies exact image content.",
            },
            {
              question: "Which tools scan container images for known vulnerabilities? (Select all that apply)",
              type: "multi_select",
              options: ["Trivy", "Grype", "kube-proxy", "CoreDNS"],
              answer: ["Trivy", "Grype"],
              explanation: "Trivy and Grype are image vulnerability scanners. kube-proxy and CoreDNS are cluster components.",
            },
            {
              question: "What does Sigstore cosign let you do?",
              type: "multiple_choice",
              options: [
                "Sign container images and verify the signatures",
                "Encrypt etcd",
                "Scan nodes for rootkits",
                "Rotate ServiceAccount tokens",
              ],
              answer: "Sign container images and verify the signatures",
              explanation: "cosign signs images and verifies them. Admission controllers can require valid signatures before Pods run.",
            },
            {
              question: "Moving a password from a ConfigMap into a Secret is enough; there is no need to rotate it.",
              type: "true_false",
              options: ["True", "False"],
              answer: "False",
              explanation: "A credential stored in plain text may already have been read or committed. Treat it as leaked and rotate it.",
            },
            {
              question: "Which API server feature encrypts Secrets stored in etcd?",
              type: "multiple_choice",
              options: ["EncryptionConfiguration", "AdmissionConfiguration", "AuditPolicy", "PodSecurity"],
              answer: "EncryptionConfiguration",
              explanation: "Passing an EncryptionConfiguration with --encryption-provider-config enables encryption at rest, for example with aescbc or a KMS provider.",
            },
          ],
        },
        {
          type: "lab",
          slug: "secrets-hygiene-lab",
          title: "Lab: Fix Leaked Credentials and Unpinned Images",
          duration: 20,
          xp: 150,
          intro: "Move a leaked password into a Secret and pin an image version.",
          timeLimit: 25,
          hints: [
            "kubectl create secret generic billing-db --from-literal=DB_PASSWORD=N3w-Pa55-2024 -n billing",
            "kubectl delete configmap billing-config -n billing",
            "kubectl create configmap billing-config --from-literal=DB_HOST=db -n billing",
            "kubectl set image deployment/billing nginx=nginx:1.27.2 -n billing",
          ],
          initialState: [
            { kind: "Namespace", name: "billing" },
            { kind: "ConfigMap", name: "billing-config", namespace: "billing", data: { DB_HOST: "db", DB_PASSWORD: "hunter2" } },
            { kind: "Deployment", name: "billing", namespace: "billing", image: "nginx:latest", replicas: 2, revisions: ["nginx:latest"], labels: { app: "billing" } },
          ],
          checks: [
            { type: "exists", description: "Secret billing-db holds the rotated password", kind: "Secret", name: "billing-db", namespace: "billing", match: { data: { DB_PASSWORD: "N3w-Pa55-2024" } } },
            { type: "exists", description: "billing-config only holds DB_HOST", kind: "ConfigMap", name: "billing-config", namespace: "billing", match: { data: { DB_HOST: "db" } }, absentKeys: ["DB_PASSWORD"] },
            { type: "exists", description: "billing is pinned to nginx:1.27.2", kind: "Deployment", name: "billing", namespace: "billing", match: { image: "nginx:1.27.2" } },
          ],
        },
      ],
    },
  ],
};
