import type { CertificationContent } from "./types";

export const kcna: CertificationContent = {
  slug: "kcna",
  name: "Kubernetes and Cloud Native Associate",
  shortName: "KCNA",
  description:
    "A pre-professional certification designed for candidates interested in advancing to the professional level through a demonstrated understanding of Kubernetes and cloud native technologies.",
  icon: "🌱",
  color: "#10B981",
  difficulty: "beginner",
  estimatedHours: 20,
  order: 1,
  exam: { questions: 15, minutes: 25, passPercent: 75 },
  modules: [
    {
      slug: "k8s-fundamentals",
      name: "Kubernetes Fundamentals",
      description: "Core concepts of Kubernetes architecture and components",
      xp: 200,
      lessons: [
        { type: "reading", slug: "what-is-kubernetes", title: "What is Kubernetes?", duration: 10, xp: 50 },
        { type: "reading", slug: "kubernetes-architecture", title: "Kubernetes Architecture", duration: 15, xp: 50 },
        {
          type: "quiz",
          slug: "fundamentals-quiz",
          title: "Kubernetes Fundamentals Quiz",
          duration: 10,
          xp: 75,
          intro: "Test your understanding of Kubernetes fundamentals.",
          questions: [
            {
              question: "Which component stores all cluster data in Kubernetes?",
              type: "multiple_choice",
              options: ["kube-apiserver", "etcd", "kube-scheduler", "kubelet"],
              answer: "etcd",
              explanation: "etcd is the consistent and highly-available key-value store that serves as Kubernetes' backing store for all cluster data.",
              xp: 15,
            },
            {
              question: "What is the smallest deployable unit in Kubernetes?",
              type: "multiple_choice",
              options: ["Container", "Pod", "Deployment", "Node"],
              answer: "Pod",
              explanation: "A Pod is the smallest deployable unit in Kubernetes. It can contain one or more containers that share storage and network resources.",
              xp: 15,
            },
            {
              question: "Kubernetes was originally designed by Google based on their internal system called Borg.",
              type: "true_false",
              options: ["True", "False"],
              answer: "True",
              explanation: "Kubernetes was based on Google's internal Borg system, which managed containerized workloads at scale for over 15 years.",
              xp: 10,
            },
            {
              question: "Which components run on every worker node? (Select all that apply)",
              type: "multi_select",
              options: ["kubelet", "kube-proxy", "Container Runtime", "kube-scheduler", "etcd"],
              answer: ["kubelet", "kube-proxy", "Container Runtime"],
              explanation: "kubelet, kube-proxy and the container runtime run on every worker node. kube-scheduler and etcd are control plane components.",
              xp: 20,
            },
            {
              question: "What does the kube-scheduler do?",
              type: "multiple_choice",
              options: [
                "Stores cluster state",
                "Assigns newly created pods to nodes",
                "Manages network rules",
                "Runs containers on nodes",
              ],
              answer: "Assigns newly created pods to nodes",
              explanation: "The kube-scheduler watches for new Pods with no node assigned and picks the best node for each based on resources and constraints.",
              xp: 15,
            },
          ],
        },
        {
          type: "lab",
          slug: "explore-cluster-lab",
          title: "Lab: Explore a Kubernetes Cluster",
          duration: 15,
          xp: 100,
          intro: "In this lab you'll use kubectl to explore a running cluster and its components.",
          timeLimit: 30,
          hints: [
            "kubectl version",
            "kubectl get nodes",
            "kubectl get namespaces",
            "kubectl get pods -A",
            "kubectl cluster-info",
            "kubectl describe node worker-1",
          ],
          checks: [
            { type: "command", description: "Checked the cluster version", pattern: "^k(ubectl)?\\s+version" },
            { type: "command", description: "Listed the nodes", pattern: "get\\s+(nodes|node|no)\\b" },
            { type: "command", description: "Listed the namespaces", pattern: "get\\s+(namespaces|namespace|ns)\\b" },
            { type: "command", description: "Listed pods in all namespaces", pattern: "get\\s+(pods|pod|po)\\b.*(-A|--all-namespaces)" },
            { type: "command", description: "Showed cluster info", pattern: "cluster-info" },
            { type: "command", description: "Described worker-1", pattern: "describe\\s+(nodes?|no)[\\s/]+worker-1" },
          ],
        },
      ],
    },
    {
      slug: "cloud-native-concepts",
      name: "Cloud Native Concepts",
      description: "Understanding containers, microservices, and cloud native principles",
      xp: 200,
      lessons: [
        { type: "reading", slug: "containers-101", title: "Containers 101", duration: 12, xp: 50 },
        { type: "reading", slug: "microservices-architecture", title: "Microservices Architecture", duration: 12, xp: 50 },
        {
          type: "quiz",
          slug: "cloud-native-quiz",
          title: "Cloud Native Quiz",
          duration: 10,
          xp: 75,
          intro: "Check your understanding of containers and microservices.",
          questions: [
            {
              question: "What do containers on the same host share?",
              type: "multiple_choice",
              options: ["The host operating system kernel", "A full guest operating system", "A hypervisor per container", "Nothing at all"],
              answer: "The host operating system kernel",
              explanation: "Containers are isolated processes that share the host kernel. That's why they start faster and use less memory than virtual machines.",
            },
            {
              question: "Which Linux features provide container isolation and resource limits? (Select all that apply)",
              type: "multi_select",
              options: ["Namespaces", "cgroups", "Hypervisors", "BIOS"],
              answer: ["Namespaces", "cgroups"],
              explanation: "Namespaces isolate what a process can see (PIDs, network, mounts), and cgroups limit what it can use (CPU, memory).",
            },
            {
              question: "A container image is mutable: changes made in a running container are saved back into the image.",
              type: "true_false",
              options: ["True", "False"],
              answer: "False",
              explanation: "Images are immutable layers. A running container writes to a thin writable layer that is discarded with the container.",
            },
            {
              question: "Which is a key benefit of a microservices architecture?",
              type: "multiple_choice",
              options: [
                "Each service can be deployed and scaled independently",
                "All services must share one database",
                "There is no network communication between services",
                "The whole application is deployed at once",
              ],
              answer: "Each service can be deployed and scaled independently",
              explanation: "Microservices are independently deployable and scalable, at the cost of more network communication and operational complexity.",
            },
            {
              question: "Which organisation hosts Kubernetes and certifies KCNA, CKA, CKAD and CKS?",
              type: "multiple_choice",
              options: ["Cloud Native Computing Foundation (CNCF)", "Apache Software Foundation", "Open Container Initiative", "Docker Inc."],
              answer: "Cloud Native Computing Foundation (CNCF)",
              explanation: "The CNCF, part of the Linux Foundation, hosts Kubernetes and runs its certification programmes.",
            },
          ],
        },
        {
          type: "lab",
          slug: "first-pod-lab",
          title: "Lab: Your First Pod",
          duration: 15,
          xp: 100,
          intro: "Create a namespace and run your first Pod in it.",
          timeLimit: 20,
          hints: [
            "kubectl create namespace sandbox",
            "kubectl run web --image=nginx:1.27 -n sandbox",
            "kubectl label pod web tier=frontend -n sandbox",
            "kubectl get pods -n sandbox --show-labels",
          ],
          checks: [
            { type: "exists", description: "Namespace sandbox exists", kind: "Namespace", name: "sandbox" },
            { type: "exists", description: "Pod web runs nginx:1.27 in sandbox", kind: "Pod", name: "web", namespace: "sandbox", match: { image: "nginx:1.27" } },
            { type: "exists", description: "Pod web is labelled tier=frontend", kind: "Pod", name: "web", namespace: "sandbox", match: { labels: { tier: "frontend" } } },
          ],
        },
      ],
    },
    {
      slug: "kubernetes-objects",
      name: "Kubernetes Objects",
      description: "Workloads, Services and the labels that connect them",
      xp: 200,
      lessons: [
        { type: "reading", slug: "workloads-services-labels", title: "Workloads, Services and Labels", duration: 15, xp: 50 },
        {
          type: "quiz",
          slug: "kubernetes-objects-quiz",
          title: "Kubernetes Objects Quiz",
          duration: 10,
          xp: 75,
          intro: "Test what you know about workloads and Services.",
          questions: [
            {
              question: "Which workload type ensures exactly one Pod runs on every node?",
              type: "multiple_choice",
              options: ["Deployment", "DaemonSet", "StatefulSet", "Job"],
              answer: "DaemonSet",
              explanation: "A DaemonSet runs one copy of a Pod on each (matching) node, which is ideal for node agents like log collectors and kube-proxy.",
            },
            {
              question: "What is the default Service type?",
              type: "multiple_choice",
              options: ["NodePort", "LoadBalancer", "ClusterIP", "ExternalName"],
              answer: "ClusterIP",
              explanation: "ClusterIP is the default. It exposes the Service on an internal IP reachable only from inside the cluster.",
            },
            {
              question: "How does a Service decide which Pods receive its traffic?",
              type: "multiple_choice",
              options: ["By Pod name prefix", "By matching its label selector", "By the Deployment it was created from", "By namespace only"],
              answer: "By matching its label selector",
              explanation: "Services route to every ready Pod whose labels match the Service's selector.",
            },
            {
              question: "Which workloads suit a database that needs stable network identity and storage? (Select all that apply)",
              type: "multi_select",
              options: ["StatefulSet", "Deployment", "CronJob"],
              answer: ["StatefulSet"],
              explanation: "StatefulSets give each Pod a stable name, stable DNS and its own persistent volume claim.",
            },
            {
              question: "If a Pod managed by a Deployment is deleted, it is replaced automatically.",
              type: "true_false",
              options: ["True", "False"],
              answer: "True",
              explanation: "The Deployment's ReplicaSet notices fewer Pods than desired and creates a replacement.",
            },
          ],
        },
        {
          type: "lab",
          slug: "deploy-and-expose-lab",
          title: "Lab: Deploy and Expose an App",
          duration: 20,
          xp: 100,
          intro: "Run a replicated application behind a Service.",
          timeLimit: 25,
          hints: [
            "kubectl create deployment hello --image=nginx:1.27 --replicas=2",
            "kubectl expose deployment hello --port=80",
            "kubectl scale deployment hello --replicas=3",
            "kubectl describe svc hello",
          ],
          checks: [
            { type: "exists", description: "Deployment hello runs nginx:1.27 with 3 replicas", kind: "Deployment", name: "hello", namespace: "default", match: { image: "nginx:1.27", replicas: 3 } },
            { type: "exists", description: "Service hello listens on port 80 and selects app=hello", kind: "Service", name: "hello", namespace: "default", match: { port: 80, selector: { app: "hello" } } },
            { type: "pods", description: "3 hello Pods are running", namespace: "default", selector: { app: "hello" }, running: 3 },
          ],
        },
      ],
    },
  ],
};
