import * as path from "node:path";
import { Construct } from "constructs";
import { Duration, IgnoreMode } from "aws-cdk-lib";
import * as ec2 from "aws-cdk-lib/aws-ec2";
import * as ecs from "aws-cdk-lib/aws-ecs";
import * as elbv2 from "aws-cdk-lib/aws-elasticloadbalancingv2";
import * as logs from "aws-cdk-lib/aws-logs";
import * as rds from "aws-cdk-lib/aws-rds";
import * as secretsmanager from "aws-cdk-lib/aws-secretsmanager";
import { Platform } from "aws-cdk-lib/aws-ecr-assets";

export interface AppServiceProps {
  // VPC created by the Network construct
  vpc: ec2.IVpc;
  // RDS instance the app connects to
  database: rds.DatabaseInstance;
  // Name of the Postgres database
  databaseName: string;
  // Secret value CloudFront sends in a header; requests without it are rejected
  originVerifySecret: secretsmanager.ISecret;
}

// Header CloudFront adds to every request it forwards to the load balancer
export const ORIGIN_VERIFY_HEADER = "X-Origin-Verify";

export class AppService extends Construct {
  // Internet-facing load balancer, used as the CloudFront origin
  public readonly loadBalancer: elbv2.ApplicationLoadBalancer;
  // The app container, so the stack can add NEXTAUTH_URL once CloudFront exists
  public readonly container: ecs.ContainerDefinition;

  constructor(scope: Construct, id: string, props: AppServiceProps) {
    super(scope, id);

    // Random secret used by NextAuth to sign session tokens
    const nextAuthSecret = new secretsmanager.Secret(this, "NextAuthSecret", {
      // 48 random characters without punctuation
      generateSecretString: { passwordLength: 48, excludePunctuation: true },
    });

    // ECS cluster that groups the Fargate tasks
    const cluster = new ecs.Cluster(this, "Cluster", {
      // Place the cluster in our VPC
      vpc: props.vpc,
      // CPU/memory metrics per task in CloudWatch
      containerInsightsV2: ecs.ContainerInsights.ENABLED,
    });

    // Task definition: the size of each container instance
    const taskDefinition = new ecs.FargateTaskDefinition(this, "Task", {
      // 0.5 vCPU
      cpu: 512,
      // 1 GiB of memory
      memoryLimitMiB: 1024,
      // Build and run on x86_64 so images built on standard CI agents match
      runtimePlatform: {
        cpuArchitecture: ecs.CpuArchitecture.X86_64,
        operatingSystemFamily: ecs.OperatingSystemFamily.LINUX,
      },
    });

    // The database secret generated by RDS (contains username and password)
    const dbSecret = props.database.secret;
    // RDS always creates it when credentials are generated; fail loudly otherwise
    if (dbSecret === undefined) throw new Error("Database secret is missing");

    this.container = taskDefinition.addContainer("App", {
      // Build the image from the repository root Dockerfile during "cdk deploy" and push it to ECR
      image: ecs.ContainerImage.fromAsset(path.join(__dirname, "..", "..", ".."), {
        // Use .dockerignore rules for the build context
        ignoreMode: IgnoreMode.DOCKER,
        // Never send the infra folder (and its cdk.out) into the Docker build
        exclude: ["infra"],
        // Match the task's CPU architecture
        platform: Platform.LINUX_AMD64,
      }),
      // Send stdout/stderr to CloudWatch Logs, kept for one month
      logging: ecs.LogDrivers.awsLogs({ streamPrefix: "kubelearn", logRetention: logs.RetentionDays.ONE_MONTH }),
      // Non-secret configuration
      environment: {
        // Production mode for Next.js
        NODE_ENV: "production",
        // Apply content from prisma/content on every start (idempotent)
        SEED_ON_START: "true",
        // Database endpoint used by docker-entrypoint.sh to build DATABASE_URL
        DB_HOST: props.database.dbInstanceEndpointAddress,
        // Database port
        DB_PORT: props.database.dbInstanceEndpointPort,
        // Database name
        DB_NAME: props.databaseName,
      },
      // Secrets are injected at start-up by ECS and never appear in the task definition
      secrets: {
        // Database user from the RDS secret
        DB_USERNAME: ecs.Secret.fromSecretsManager(dbSecret, "username"),
        // Database password from the RDS secret
        DB_PASSWORD: ecs.Secret.fromSecretsManager(dbSecret, "password"),
        // NextAuth signing key
        NEXTAUTH_SECRET: ecs.Secret.fromSecretsManager(nextAuthSecret),
      },
      // Next.js standalone server port (set in the Dockerfile)
      portMappings: [{ containerPort: 3000 }],
    });

    // Fargate service keeps the desired number of tasks running
    const service = new ecs.FargateService(this, "Service", {
      // Run in our cluster
      cluster,
      // With the task definition above
      taskDefinition,
      // Two tasks for availability across both AZs
      desiredCount: 2,
      // Tasks live in private subnets and are only reachable through the load balancer
      vpcSubnets: { subnetType: ec2.SubnetType.PRIVATE_WITH_EGRESS },
      // Automatically roll back a deployment whose tasks keep failing health checks
      circuitBreaker: { rollback: true },
      // Keep full capacity during deployments
      minHealthyPercent: 100,
      // Give start-up (migrations + seed) time before health checks count
      healthCheckGracePeriod: Duration.seconds(120),
    });

    // Scale between 2 and 6 tasks based on CPU usage
    const scaling = service.autoScaleTaskCount({ minCapacity: 2, maxCapacity: 6 });
    // Add a task when average CPU stays above 60%
    scaling.scaleOnCpuUtilization("Cpu", { targetUtilizationPercent: 60 });

    // Allow the app tasks (and only them) to reach Postgres on its port
    props.database.connections.allowDefaultPortFrom(service, "App tasks to Postgres");

    // Public load balancer in the public subnets
    this.loadBalancer = new elbv2.ApplicationLoadBalancer(this, "Alb", {
      // Place it in our VPC
      vpc: props.vpc,
      // Reachable from the internet so CloudFront can connect
      internetFacing: true,
      // Drop malformed HTTP headers instead of forwarding them
      dropInvalidHeaderFields: true,
    });

    // HTTP listener; by default every request is refused
    const listener = this.loadBalancer.addListener("Http", {
      // CloudFront connects to the origin over HTTP on port 80
      port: 80,
      // Anything that didn't come through CloudFront gets a 403
      defaultAction: elbv2.ListenerAction.fixedResponse(403, { contentType: "text/plain", messageBody: "Forbidden" }),
    });

    // Forward to the app only when the secret CloudFront header is present
    listener.addTargets("App", {
      // Rule evaluation order (lower runs first)
      priority: 1,
      // Match on the shared secret header value
      conditions: [
        elbv2.ListenerCondition.httpHeader(ORIGIN_VERIFY_HEADER, [
          props.originVerifySecret.secretValue.unsafeUnwrap(),
        ]),
      ],
      // Plain HTTP between the load balancer and the containers inside the VPC
      protocol: elbv2.ApplicationProtocol.HTTP,
      // Register the Fargate tasks as targets
      targets: [service],
      // Health check against the (static) home page
      healthCheck: {
        // Path the load balancer requests
        path: "/",
        // Treat HTTP 200 as healthy
        healthyHttpCodes: "200",
        // Check every 30 seconds
        interval: Duration.seconds(30),
      },
      // Wait only 30s for in-flight requests when a task is replaced
      deregistrationDelay: Duration.seconds(30),
    });
  }
}
